### ISSUE TITLE
Add points (MMR) for ranking players

### ISSUE THREAD

**Issue by mattwells19** [ClamSageCaleb/UNCC-SIX-MANS#29]
Stakeholders would like Norm to rank players in a more intelligent way. The current working theory is to have a new metric called points or MMR. Players would gain, never lose, MMR, if they win, based on the MMR of their teammates and of the opposing team. How this is balanced has not been fully decided and will need feedback with stakeholders throughout it's development.

**Comment by N0ise9** [comment]
An issue was brought to my attention that players would be able to "farm" other players if they did **not** lose MMR. 
For example:
Let's assume a good Rocket League player is able to achieve first on the leaderboard. Even though that player will not receive a lot of MMR for winning their matches, as they are first on the leaderboard, they may still potentially dominate most 6 Mans queues. They can win a little MMR a lot of times and still create a skill gap large enough to be hard to overcome for any member.

To negate this, the idea was proposed that when the "Captains" option was picked - take the 3 highest ranked people in each 6 Mans queue, randomly pick two of the three to be captains. This way, it still remains that the highest-ranked people will most likely be pitted against each other to minimize the possibility to dominate 6 Mans. 

Along with this, it was proposed to also still take away MMR for losing a match. The weighted MMR loss will be calculated just like MMR gains for winning. The reason being is that if for some reason the best player in UNCC 6 Mans were able to dominate, they would have a heavy MMR loss for losing a match which would make it harder for the MMR gap to be large. The counter-argument to this was that it would make people not want to play 6 Mans. Not taking away MMR for losing, definitely helps out those that are not as good at Rocket League, and keeps them from feeling down. However, this also helps out the top end as now the best players also won't lose any MMR for losing a match. 

In order to truly move to an MMR-based leaderboard, instead of wins/losses, MMR will need to be lost in order to make it fair for everyone.

**Comment by N0ise9** [comment]
After much consideration and input from stakeholders the following items are going to be the direction to move in.

- Each 6 Mans queue will return + or - MMR based on a weighted team average. No individual MMR calculations.
- Selecting the captains option will result in the top 2 MMR-based players in the queue being the captains.
- There will be the addition to allow for "Double MMR" events.
- The minimum MMR gain/loss will be 5. 
- The maximum MMR gain/loss will be 15.
- Every new player will start with 100 MMR.
